<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/plugins/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/materialize.js"></script>
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/plugins.js"></script>
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/custom-script.js"></script>
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/plugins/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/plugins/stepper/materialize-stepper.min.js"></script> 
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/jquery.numeric.js"></script> 
<script type="text/javascript" src="<?php echo $ruta ?>recursos/js/plugins/formatter/jquery.formatter.min.js"></script>   